//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.12 at 03:51:35 PM CET 
//


package org.dmtf.schemas.wbem.wscim._1.cim_schema._2.cim_softwareidentity;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import org.dmtf.schemas.wbem.wscim._1.common.CimBoolean;
import org.dmtf.schemas.wbem.wscim._1.common.CimDateTime;
import org.dmtf.schemas.wbem.wscim._1.common.CimString;
import org.dmtf.schemas.wbem.wscim._1.common.CimUnsignedLong;
import org.dmtf.schemas.wbem.wscim._1.common.CimUnsignedShort;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.dmtf.schemas.wbem.wscim._1.cim_schema._2.cim_softwareidentity package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MinExtendedResourceTypeBuildNumber_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "MinExtendedResourceTypeBuildNumber");
    private final static QName _InstallDate_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "InstallDate");
    private final static QName _MinorVersion_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "MinorVersion");
    private final static QName _OperationalStatus_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "OperationalStatus");
    private final static QName _TargetOperatingSystems_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "TargetOperatingSystems");
    private final static QName _PrimaryStatus_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "PrimaryStatus");
    private final static QName _StatusDescriptions_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "StatusDescriptions");
    private final static QName _Caption_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "Caption");
    private final static QName _RevisionNumber_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "RevisionNumber");
    private final static QName _MinExtendedResourceTypeMinorVersion_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "MinExtendedResourceTypeMinorVersion");
    private final static QName _ExtendedResourceType_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "ExtendedResourceType");
    private final static QName _Classifications_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "Classifications");
    private final static QName _MinExtendedResourceTypeRevisionNumber_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "MinExtendedResourceTypeRevisionNumber");
    private final static QName _HealthState_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "HealthState");
    private final static QName _DetailedStatus_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "DetailedStatus");
    private final static QName _TargetOSTypes_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "TargetOSTypes");
    private final static QName _CommunicationStatus_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "CommunicationStatus");
    private final static QName _InstanceID_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "InstanceID");
    private final static QName _SerialNumber_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "SerialNumber");
    private final static QName _IdentityInfoValue_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "IdentityInfoValue");
    private final static QName _Manufacturer_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "Manufacturer");
    private final static QName _Name_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "Name");
    private final static QName _IsLargeBuildNumber_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "IsLargeBuildNumber");
    private final static QName _VersionString_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "VersionString");
    private final static QName _BuildNumber_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "BuildNumber");
    private final static QName _IdentityInfoType_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "IdentityInfoType");
    private final static QName _IsEntity_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "IsEntity");
    private final static QName _LargeBuildNumber_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "LargeBuildNumber");
    private final static QName _OtherExtendedResourceTypeDescription_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "OtherExtendedResourceTypeDescription");
    private final static QName _CIMSoftwareIdentity_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "CIM_SoftwareIdentity");
    private final static QName _OperatingStatus_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "OperatingStatus");
    private final static QName _Languages_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "Languages");
    private final static QName _TargetTypes_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "TargetTypes");
    private final static QName _ClassificationDescriptions_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "ClassificationDescriptions");
    private final static QName _ElementName_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "ElementName");
    private final static QName _MajorVersion_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "MajorVersion");
    private final static QName _MinExtendedResourceTypeMajorVersion_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "MinExtendedResourceTypeMajorVersion");
    private final static QName _ReleaseDate_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "ReleaseDate");
    private final static QName _Status_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "Status");
    private final static QName _Description_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", "Description");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.dmtf.schemas.wbem.wscim._1.cim_schema._2.cim_softwareidentity
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Caption }
     * 
     */
    public Caption createCaption() {
        return new Caption();
    }

    /**
     * Create an instance of {@link HealthState }
     * 
     */
    public HealthState createHealthState() {
        return new HealthState();
    }

    /**
     * Create an instance of {@link TargetOSTypes }
     * 
     */
    public TargetOSTypes createTargetOSTypes() {
        return new TargetOSTypes();
    }

    /**
     * Create an instance of {@link OperatingStatus }
     * 
     */
    public OperatingStatus createOperatingStatus() {
        return new OperatingStatus();
    }

    /**
     * Create an instance of {@link IdentityInfoValue }
     * 
     */
    public IdentityInfoValue createIdentityInfoValue() {
        return new IdentityInfoValue();
    }

    /**
     * Create an instance of {@link DetailedStatus }
     * 
     */
    public DetailedStatus createDetailedStatus() {
        return new DetailedStatus();
    }

    /**
     * Create an instance of {@link OperationalStatus }
     * 
     */
    public OperationalStatus createOperationalStatus() {
        return new OperationalStatus();
    }

    /**
     * Create an instance of {@link IdentityInfoType }
     * 
     */
    public IdentityInfoType createIdentityInfoType() {
        return new IdentityInfoType();
    }

    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link CommunicationStatus }
     * 
     */
    public CommunicationStatus createCommunicationStatus() {
        return new CommunicationStatus();
    }

    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link ExtendedResourceType }
     * 
     */
    public ExtendedResourceType createExtendedResourceType() {
        return new ExtendedResourceType();
    }

    /**
     * Create an instance of {@link CIMSoftwareIdentityType }
     * 
     */
    public CIMSoftwareIdentityType createCIMSoftwareIdentityType() {
        return new CIMSoftwareIdentityType();
    }

    /**
     * Create an instance of {@link Classifications }
     * 
     */
    public Classifications createClassifications() {
        return new Classifications();
    }

    /**
     * Create an instance of {@link PrimaryStatus }
     * 
     */
    public PrimaryStatus createPrimaryStatus() {
        return new PrimaryStatus();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimUnsignedShort }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "MinExtendedResourceTypeBuildNumber")
    public JAXBElement<CimUnsignedShort> createMinExtendedResourceTypeBuildNumber(CimUnsignedShort value) {
        return new JAXBElement<CimUnsignedShort>(_MinExtendedResourceTypeBuildNumber_QNAME, CimUnsignedShort.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimDateTime }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "InstallDate")
    public JAXBElement<CimDateTime> createInstallDate(CimDateTime value) {
        return new JAXBElement<CimDateTime>(_InstallDate_QNAME, CimDateTime.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimUnsignedShort }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "MinorVersion")
    public JAXBElement<CimUnsignedShort> createMinorVersion(CimUnsignedShort value) {
        return new JAXBElement<CimUnsignedShort>(_MinorVersion_QNAME, CimUnsignedShort.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OperationalStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "OperationalStatus")
    public JAXBElement<OperationalStatus> createOperationalStatus(OperationalStatus value) {
        return new JAXBElement<OperationalStatus>(_OperationalStatus_QNAME, OperationalStatus.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "TargetOperatingSystems")
    public JAXBElement<CimString> createTargetOperatingSystems(CimString value) {
        return new JAXBElement<CimString>(_TargetOperatingSystems_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrimaryStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "PrimaryStatus")
    public JAXBElement<PrimaryStatus> createPrimaryStatus(PrimaryStatus value) {
        return new JAXBElement<PrimaryStatus>(_PrimaryStatus_QNAME, PrimaryStatus.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "StatusDescriptions")
    public JAXBElement<CimString> createStatusDescriptions(CimString value) {
        return new JAXBElement<CimString>(_StatusDescriptions_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Caption }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "Caption")
    public JAXBElement<Caption> createCaption(Caption value) {
        return new JAXBElement<Caption>(_Caption_QNAME, Caption.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimUnsignedShort }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "RevisionNumber")
    public JAXBElement<CimUnsignedShort> createRevisionNumber(CimUnsignedShort value) {
        return new JAXBElement<CimUnsignedShort>(_RevisionNumber_QNAME, CimUnsignedShort.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimUnsignedShort }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "MinExtendedResourceTypeMinorVersion")
    public JAXBElement<CimUnsignedShort> createMinExtendedResourceTypeMinorVersion(CimUnsignedShort value) {
        return new JAXBElement<CimUnsignedShort>(_MinExtendedResourceTypeMinorVersion_QNAME, CimUnsignedShort.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtendedResourceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "ExtendedResourceType")
    public JAXBElement<ExtendedResourceType> createExtendedResourceType(ExtendedResourceType value) {
        return new JAXBElement<ExtendedResourceType>(_ExtendedResourceType_QNAME, ExtendedResourceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Classifications }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "Classifications")
    public JAXBElement<Classifications> createClassifications(Classifications value) {
        return new JAXBElement<Classifications>(_Classifications_QNAME, Classifications.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimUnsignedShort }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "MinExtendedResourceTypeRevisionNumber")
    public JAXBElement<CimUnsignedShort> createMinExtendedResourceTypeRevisionNumber(CimUnsignedShort value) {
        return new JAXBElement<CimUnsignedShort>(_MinExtendedResourceTypeRevisionNumber_QNAME, CimUnsignedShort.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HealthState }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "HealthState")
    public JAXBElement<HealthState> createHealthState(HealthState value) {
        return new JAXBElement<HealthState>(_HealthState_QNAME, HealthState.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DetailedStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "DetailedStatus")
    public JAXBElement<DetailedStatus> createDetailedStatus(DetailedStatus value) {
        return new JAXBElement<DetailedStatus>(_DetailedStatus_QNAME, DetailedStatus.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TargetOSTypes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "TargetOSTypes")
    public JAXBElement<TargetOSTypes> createTargetOSTypes(TargetOSTypes value) {
        return new JAXBElement<TargetOSTypes>(_TargetOSTypes_QNAME, TargetOSTypes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommunicationStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "CommunicationStatus")
    public JAXBElement<CommunicationStatus> createCommunicationStatus(CommunicationStatus value) {
        return new JAXBElement<CommunicationStatus>(_CommunicationStatus_QNAME, CommunicationStatus.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "InstanceID")
    public JAXBElement<CimString> createInstanceID(CimString value) {
        return new JAXBElement<CimString>(_InstanceID_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "SerialNumber")
    public JAXBElement<CimString> createSerialNumber(CimString value) {
        return new JAXBElement<CimString>(_SerialNumber_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentityInfoValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "IdentityInfoValue")
    public JAXBElement<IdentityInfoValue> createIdentityInfoValue(IdentityInfoValue value) {
        return new JAXBElement<IdentityInfoValue>(_IdentityInfoValue_QNAME, IdentityInfoValue.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "Manufacturer")
    public JAXBElement<CimString> createManufacturer(CimString value) {
        return new JAXBElement<CimString>(_Manufacturer_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Name }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "Name")
    public JAXBElement<Name> createName(Name value) {
        return new JAXBElement<Name>(_Name_QNAME, Name.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimBoolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "IsLargeBuildNumber")
    public JAXBElement<CimBoolean> createIsLargeBuildNumber(CimBoolean value) {
        return new JAXBElement<CimBoolean>(_IsLargeBuildNumber_QNAME, CimBoolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "VersionString")
    public JAXBElement<CimString> createVersionString(CimString value) {
        return new JAXBElement<CimString>(_VersionString_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimUnsignedShort }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "BuildNumber")
    public JAXBElement<CimUnsignedShort> createBuildNumber(CimUnsignedShort value) {
        return new JAXBElement<CimUnsignedShort>(_BuildNumber_QNAME, CimUnsignedShort.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentityInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "IdentityInfoType")
    public JAXBElement<IdentityInfoType> createIdentityInfoType(IdentityInfoType value) {
        return new JAXBElement<IdentityInfoType>(_IdentityInfoType_QNAME, IdentityInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimBoolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "IsEntity")
    public JAXBElement<CimBoolean> createIsEntity(CimBoolean value) {
        return new JAXBElement<CimBoolean>(_IsEntity_QNAME, CimBoolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimUnsignedLong }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "LargeBuildNumber")
    public JAXBElement<CimUnsignedLong> createLargeBuildNumber(CimUnsignedLong value) {
        return new JAXBElement<CimUnsignedLong>(_LargeBuildNumber_QNAME, CimUnsignedLong.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "OtherExtendedResourceTypeDescription")
    public JAXBElement<CimString> createOtherExtendedResourceTypeDescription(CimString value) {
        return new JAXBElement<CimString>(_OtherExtendedResourceTypeDescription_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CIMSoftwareIdentityType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "CIM_SoftwareIdentity")
    public JAXBElement<CIMSoftwareIdentityType> createCIMSoftwareIdentity(CIMSoftwareIdentityType value) {
        return new JAXBElement<CIMSoftwareIdentityType>(_CIMSoftwareIdentity_QNAME, CIMSoftwareIdentityType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OperatingStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "OperatingStatus")
    public JAXBElement<OperatingStatus> createOperatingStatus(OperatingStatus value) {
        return new JAXBElement<OperatingStatus>(_OperatingStatus_QNAME, OperatingStatus.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "Languages")
    public JAXBElement<CimString> createLanguages(CimString value) {
        return new JAXBElement<CimString>(_Languages_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "TargetTypes")
    public JAXBElement<CimString> createTargetTypes(CimString value) {
        return new JAXBElement<CimString>(_TargetTypes_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "ClassificationDescriptions")
    public JAXBElement<CimString> createClassificationDescriptions(CimString value) {
        return new JAXBElement<CimString>(_ClassificationDescriptions_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "ElementName")
    public JAXBElement<CimString> createElementName(CimString value) {
        return new JAXBElement<CimString>(_ElementName_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimUnsignedShort }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "MajorVersion")
    public JAXBElement<CimUnsignedShort> createMajorVersion(CimUnsignedShort value) {
        return new JAXBElement<CimUnsignedShort>(_MajorVersion_QNAME, CimUnsignedShort.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimUnsignedShort }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "MinExtendedResourceTypeMajorVersion")
    public JAXBElement<CimUnsignedShort> createMinExtendedResourceTypeMajorVersion(CimUnsignedShort value) {
        return new JAXBElement<CimUnsignedShort>(_MinExtendedResourceTypeMajorVersion_QNAME, CimUnsignedShort.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimDateTime }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "ReleaseDate")
    public JAXBElement<CimDateTime> createReleaseDate(CimDateTime value) {
        return new JAXBElement<CimDateTime>(_ReleaseDate_QNAME, CimDateTime.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Status }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "Status")
    public JAXBElement<Status> createStatus(Status value) {
        return new JAXBElement<Status>(_Status_QNAME, Status.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareIdentity", name = "Description")
    public JAXBElement<CimString> createDescription(CimString value) {
        return new JAXBElement<CimString>(_Description_QNAME, CimString.class, null, value);
    }

}
