/**
 * The contents of this file are subject to the Mozilla Public License
 * Version 1.1 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS"
 * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
 * License for the specific language governing rights and limitations
 * under the License.
 *
 * The Original Code is available at https://svn.forge.morfeo-project.org/claudia
 *
 * The Initial Developer of the Original Code is Telefónica Investigación y Desarrollo S.A.U.,
 * (http://www.tid.es), Emilio Vargas 6, 28043 Madrid, Spain.
.*
 * No portions of the Code have been created by third parties.
 * All Rights Reserved.
 *
 * Contributor(s): ______________________________________.
 *
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.23 at 07:11:48 PM CET 
//


package com.telefonica.claudia.ovf;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.dmtf.schemas.ovf.envelope._1.SectionType;


/**
 * <p>Java class for AspectsSection_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AspectsSection_Type">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.dmtf.org/ovf/envelope/1}Section_Type">
 *       &lt;sequence>
 *         &lt;element name="Stateless" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="FaultProtection" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="type" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="ft"/>
 *                       &lt;enumeration value="ha"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;choice>
 *           &lt;element name="BackupCustom" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="mode" use="required">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="complete"/>
 *                         &lt;enumeration value="incremental"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/attribute>
 *                   &lt;attribute name="periodicity" use="required" type="{http://schemas.telefonica.com/claudia/ovf}Periodicity_Type" />
 *                   &lt;attribute name="expiretime" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="Backup" type="{http://schemas.telefonica.com/claudia/ovf}Backup_Type" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AspectsSection_Type", propOrder = {
    "stateless",
    "faultProtection",
    "backupCustom",
    "backup"
})
public class AspectsSectionType
    extends SectionType
{

    @XmlElement(name = "Stateless")
    protected AspectsSectionType.Stateless stateless;
    @XmlElement(name = "FaultProtection")
    protected AspectsSectionType.FaultProtection faultProtection;
    @XmlElement(name = "BackupCustom")
    protected AspectsSectionType.BackupCustom backupCustom;
    @XmlElement(name = "Backup")
    protected BackupType backup;

    /**
     * Gets the value of the stateless property.
     * 
     * @return
     *     possible object is
     *     {@link AspectsSectionType.Stateless }
     *     
     */
    public AspectsSectionType.Stateless getStateless() {
        return stateless;
    }

    /**
     * Sets the value of the stateless property.
     * 
     * @param value
     *     allowed object is
     *     {@link AspectsSectionType.Stateless }
     *     
     */
    public void setStateless(AspectsSectionType.Stateless value) {
        this.stateless = value;
    }

    /**
     * Gets the value of the faultProtection property.
     * 
     * @return
     *     possible object is
     *     {@link AspectsSectionType.FaultProtection }
     *     
     */
    public AspectsSectionType.FaultProtection getFaultProtection() {
        return faultProtection;
    }

    /**
     * Sets the value of the faultProtection property.
     * 
     * @param value
     *     allowed object is
     *     {@link AspectsSectionType.FaultProtection }
     *     
     */
    public void setFaultProtection(AspectsSectionType.FaultProtection value) {
        this.faultProtection = value;
    }

    /**
     * Gets the value of the backupCustom property.
     * 
     * @return
     *     possible object is
     *     {@link AspectsSectionType.BackupCustom }
     *     
     */
    public AspectsSectionType.BackupCustom getBackupCustom() {
        return backupCustom;
    }

    /**
     * Sets the value of the backupCustom property.
     * 
     * @param value
     *     allowed object is
     *     {@link AspectsSectionType.BackupCustom }
     *     
     */
    public void setBackupCustom(AspectsSectionType.BackupCustom value) {
        this.backupCustom = value;
    }

    /**
     * Gets the value of the backup property.
     * 
     * @return
     *     possible object is
     *     {@link BackupType }
     *     
     */
    public BackupType getBackup() {
        return backup;
    }

    /**
     * Sets the value of the backup property.
     * 
     * @param value
     *     allowed object is
     *     {@link BackupType }
     *     
     */
    public void setBackup(BackupType value) {
        this.backup = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="mode" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="complete"/>
     *             &lt;enumeration value="incremental"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="periodicity" use="required" type="{http://schemas.telefonica.com/claudia/ovf}Periodicity_Type" />
     *       &lt;attribute name="expiretime" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class BackupCustom {

        @XmlAttribute(name = "mode", required = true)
        protected String mode;
        @XmlAttribute(name = "periodicity", required = true)
        protected PeriodicityType periodicity;
        @XmlAttribute(name = "expiretime", required = true)
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger expiretime;

        /**
         * Gets the value of the mode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMode() {
            return mode;
        }

        /**
         * Sets the value of the mode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMode(String value) {
            this.mode = value;
        }

        /**
         * Gets the value of the periodicity property.
         * 
         * @return
         *     possible object is
         *     {@link PeriodicityType }
         *     
         */
        public PeriodicityType getPeriodicity() {
            return periodicity;
        }

        /**
         * Sets the value of the periodicity property.
         * 
         * @param value
         *     allowed object is
         *     {@link PeriodicityType }
         *     
         */
        public void setPeriodicity(PeriodicityType value) {
            this.periodicity = value;
        }

        /**
         * Gets the value of the expiretime property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getExpiretime() {
            return expiretime;
        }

        /**
         * Sets the value of the expiretime property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setExpiretime(BigInteger value) {
            this.expiretime = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="type" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="ft"/>
     *             &lt;enumeration value="ha"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class FaultProtection {

        @XmlAttribute(name = "type", required = true)
        protected String type;

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Stateless {

        @XmlAttribute(name = "value", required = true)
        protected boolean value;

        /**
         * Gets the value of the value property.
         * 
         */
        public boolean isValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(boolean value) {
            this.value = value;
        }

    }

}
