/**
 * The contents of this file are subject to the Mozilla Public License
 * Version 1.1 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS"
 * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
 * License for the specific language governing rights and limitations
 * under the License.
 *
 * The Original Code is available at https://svn.forge.morfeo-project.org/claudia
 *
 * The Initial Developer of the Original Code is Telefónica Investigación y Desarrollo S.A.U.,
 * (http://www.tid.es), Emilio Vargas 6, 28043 Madrid, Spain.
.*
 * No portions of the Code have been created by third parties.
 * All Rights Reserved.
 *
 * Contributor(s): ______________________________________.
 *
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.23 at 07:11:48 PM CET 
//


package com.telefonica.claudia.ovf;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LoadBalancerMember_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LoadBalancerMember_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ServerIP" type="{http://schemas.telefonica.com/claudia/ovf}IPAddress_Type"/>
 *         &lt;element name="ServicePort" type="{http://schemas.telefonica.com/claudia/ovf}Port_Type"/>
 *       &lt;/sequence>
 *       &lt;attribute name="priority" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="ratio" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoadBalancerMember_Type", propOrder = {
    "serverIP",
    "servicePort"
})
public class LoadBalancerMemberType {

    @XmlElement(name = "ServerIP", required = true)
    protected String serverIP;
    @XmlElement(name = "ServicePort")
    protected int servicePort;
    @XmlAttribute(name = "priority")
    protected Boolean priority;
    @XmlAttribute(name = "ratio")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger ratio;

    /**
     * Gets the value of the serverIP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServerIP() {
        return serverIP;
    }

    /**
     * Sets the value of the serverIP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServerIP(String value) {
        this.serverIP = value;
    }

    /**
     * Gets the value of the servicePort property.
     * 
     */
    public int getServicePort() {
        return servicePort;
    }

    /**
     * Sets the value of the servicePort property.
     * 
     */
    public void setServicePort(int value) {
        this.servicePort = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPriority(Boolean value) {
        this.priority = value;
    }

    /**
     * Gets the value of the ratio property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRatio() {
        return ratio;
    }

    /**
     * Sets the value of the ratio property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRatio(BigInteger value) {
        this.ratio = value;
    }

}
