/**
 * The contents of this file are subject to the Mozilla Public License
 * Version 1.1 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS"
 * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
 * License for the specific language governing rights and limitations
 * under the License.
 *
 * The Original Code is available at https://svn.forge.morfeo-project.org/claudia
 *
 * The Initial Developer of the Original Code is Telefónica Investigación y Desarrollo S.A.U.,
 * (http://www.tid.es), Emilio Vargas 6, 28043 Madrid, Spain.
.*
 * No portions of the Code have been created by third parties.
 * All Rights Reserved.
 *
 * Contributor(s): ______________________________________.
 *
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.23 at 07:11:48 PM CET 
//


package com.telefonica.claudia.ovf;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.telefonica.claudia.ovf package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PerformanceObjectiveSection_QNAME = new QName("http://schemas.telefonica.com/claudia/ovf", "PerformanceObjectiveSection");
    private final static QName _DeploymentSection_QNAME = new QName("http://schemas.telefonica.com/claudia/ovf", "DeploymentSection");
    private final static QName _AvailabilitySection_QNAME = new QName("http://schemas.telefonica.com/claudia/ovf", "AvailabilitySection");
    private final static QName _LoadBalancerSection_QNAME = new QName("http://schemas.telefonica.com/claudia/ovf", "LoadBalancerSection");
    private final static QName _AffinitySection_QNAME = new QName("http://schemas.telefonica.com/claudia/ovf", "AffinitySection");
    private final static QName _DiskMappingSection_QNAME = new QName("http://schemas.telefonica.com/claudia/ovf", "DiskMappingSection");
    private final static QName _FirewallSection_QNAME = new QName("http://schemas.telefonica.com/claudia/ovf", "FirewallSection");
    private final static QName _KPISection_QNAME = new QName("http://schemas.telefonica.com/claudia/ovf", "KPISection");
    private final static QName _ElasticArraySection_QNAME = new QName("http://schemas.telefonica.com/claudia/ovf", "ElasticArraySection");
    private final static QName _AspectsSection_QNAME = new QName("http://schemas.telefonica.com/claudia/ovf", "AspectsSection");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.telefonica.claudia.ovf
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LoadBalacerPoolType }
     * 
     */
    public LoadBalacerPoolType createLoadBalacerPoolType() {
        return new LoadBalacerPoolType();
    }

    /**
     * Create an instance of {@link PositionType.Location }
     * 
     */
    public PositionType.Location createPositionTypeLocation() {
        return new PositionType.Location();
    }

    /**
     * Create an instance of {@link AspectsSectionType.FaultProtection }
     * 
     */
    public AspectsSectionType.FaultProtection createAspectsSectionTypeFaultProtection() {
        return new AspectsSectionType.FaultProtection();
    }

    /**
     * Create an instance of {@link FirewallSectionType }
     * 
     */
    public FirewallSectionType createFirewallSectionType() {
        return new FirewallSectionType();
    }

    /**
     * Create an instance of {@link DeploymentSectionType }
     * 
     */
    public DeploymentSectionType createDeploymentSectionType() {
        return new DeploymentSectionType();
    }

    /**
     * Create an instance of {@link BalanceType }
     * 
     */
    public BalanceType createBalanceType() {
        return new BalanceType();
    }

    /**
     * Create an instance of {@link LoadBalancerSectionType }
     * 
     */
    public LoadBalancerSectionType createLoadBalancerSectionType() {
        return new LoadBalancerSectionType();
    }

    /**
     * Create an instance of {@link LoadBalacerPoolType.Persistence.Expiration }
     * 
     */
    public LoadBalacerPoolType.Persistence.Expiration createLoadBalacerPoolTypePersistenceExpiration() {
        return new LoadBalacerPoolType.Persistence.Expiration();
    }

    /**
     * Create an instance of {@link RestrictionType }
     * 
     */
    public RestrictionType createRestrictionType() {
        return new RestrictionType();
    }

    /**
     * Create an instance of {@link AffinitySectionType }
     * 
     */
    public AffinitySectionType createAffinitySectionType() {
        return new AffinitySectionType();
    }

    /**
     * Create an instance of {@link AntiAffinityType }
     * 
     */
    public AntiAffinityType createAntiAffinityType() {
        return new AntiAffinityType();
    }

    /**
     * Create an instance of {@link BackupType }
     * 
     */
    public BackupType createBackupType() {
        return new BackupType();
    }

    /**
     * Create an instance of {@link RuleType }
     * 
     */
    public RuleType createRuleType() {
        return new RuleType();
    }

    /**
     * Create an instance of {@link AspectsSectionType.Stateless }
     * 
     */
    public AspectsSectionType.Stateless createAspectsSectionTypeStateless() {
        return new AspectsSectionType.Stateless();
    }

    /**
     * Create an instance of {@link TimezoneType }
     * 
     */
    public TimezoneType createTimezoneType() {
        return new TimezoneType();
    }

    /**
     * Create an instance of {@link KPISectionType }
     * 
     */
    public KPISectionType createKPISectionType() {
        return new KPISectionType();
    }

    /**
     * Create an instance of {@link LoadBalacerPoolType.Persistence }
     * 
     */
    public LoadBalacerPoolType.Persistence createLoadBalacerPoolTypePersistence() {
        return new LoadBalacerPoolType.Persistence();
    }

    /**
     * Create an instance of {@link PositionType.Distance }
     * 
     */
    public PositionType.Distance createPositionTypeDistance() {
        return new PositionType.Distance();
    }

    /**
     * Create an instance of {@link LoadBalancerMemberType }
     * 
     */
    public LoadBalancerMemberType createLoadBalancerMemberType() {
        return new LoadBalancerMemberType();
    }

    /**
     * Create an instance of {@link AreaType }
     * 
     */
    public AreaType createAreaType() {
        return new AreaType();
    }

    /**
     * Create an instance of {@link AffinityType }
     * 
     */
    public AffinityType createAffinityType() {
        return new AffinityType();
    }

    /**
     * Create an instance of {@link ElasticArraySectionType }
     * 
     */
    public ElasticArraySectionType createElasticArraySectionType() {
        return new ElasticArraySectionType();
    }

    /**
     * Create an instance of {@link DiskMapType }
     * 
     */
    public DiskMapType createDiskMapType() {
        return new DiskMapType();
    }

    /**
     * Create an instance of {@link FirewallPoolType }
     * 
     */
    public FirewallPoolType createFirewallPoolType() {
        return new FirewallPoolType();
    }

    /**
     * Create an instance of {@link DiskMappingSectionType }
     * 
     */
    public DiskMappingSectionType createDiskMappingSectionType() {
        return new DiskMappingSectionType();
    }

    /**
     * Create an instance of {@link FirewallRuleType }
     * 
     */
    public FirewallRuleType createFirewallRuleType() {
        return new FirewallRuleType();
    }

    /**
     * Create an instance of {@link KPISectionType.KPI }
     * 
     */
    public KPISectionType.KPI createKPISectionTypeKPI() {
        return new KPISectionType.KPI();
    }

    /**
     * Create an instance of {@link LoadBalacerPoolType.HealthMonitor }
     * 
     */
    public LoadBalacerPoolType.HealthMonitor createLoadBalacerPoolTypeHealthMonitor() {
        return new LoadBalacerPoolType.HealthMonitor();
    }

    /**
     * Create an instance of {@link PositionType }
     * 
     */
    public PositionType createPositionType() {
        return new PositionType();
    }

    /**
     * Create an instance of {@link AspectsSectionType }
     * 
     */
    public AspectsSectionType createAspectsSectionType() {
        return new AspectsSectionType();
    }

    /**
     * Create an instance of {@link AspectsSectionType.BackupCustom }
     * 
     */
    public AspectsSectionType.BackupCustom createAspectsSectionTypeBackupCustom() {
        return new AspectsSectionType.BackupCustom();
    }

    /**
     * Create an instance of {@link WindowType }
     * 
     */
    public WindowType createWindowType() {
        return new WindowType();
    }

    /**
     * Create an instance of {@link CountryType }
     * 
     */
    public CountryType createCountryType() {
        return new CountryType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DiskMappingSectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.telefonica.com/claudia/ovf", name = "DiskMappingSection", substitutionHeadNamespace = "http://schemas.dmtf.org/ovf/envelope/1", substitutionHeadName = "Section")
    public JAXBElement<DiskMappingSectionType> createDiskMappingSection(DiskMappingSectionType value) {
        return new JAXBElement<DiskMappingSectionType>(_DiskMappingSection_QNAME, DiskMappingSectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FirewallSectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.telefonica.com/claudia/ovf", name = "FirewallSection", substitutionHeadNamespace = "http://schemas.dmtf.org/ovf/envelope/1", substitutionHeadName = "Section")
    public JAXBElement<FirewallSectionType> createFirewallSection(FirewallSectionType value) {
        return new JAXBElement<FirewallSectionType>(_FirewallSection_QNAME, FirewallSectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElasticArraySectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.telefonica.com/claudia/ovf", name = "ElasticArraySection", substitutionHeadNamespace = "http://schemas.dmtf.org/ovf/envelope/1", substitutionHeadName = "Section")
    public JAXBElement<ElasticArraySectionType> createElasticArraySection(ElasticArraySectionType value) {
        return new JAXBElement<ElasticArraySectionType>(_ElasticArraySection_QNAME, ElasticArraySectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AspectsSectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.telefonica.com/claudia/ovf", name = "AspectsSection", substitutionHeadNamespace = "http://schemas.dmtf.org/ovf/envelope/1", substitutionHeadName = "Section")
    public JAXBElement<AspectsSectionType> createAspectsSection(AspectsSectionType value) {
        return new JAXBElement<AspectsSectionType>(_AspectsSection_QNAME, AspectsSectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KPISectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.telefonica.com/claudia/ovf", name = "KPISection", substitutionHeadNamespace = "http://schemas.dmtf.org/ovf/envelope/1", substitutionHeadName = "Section")
    public JAXBElement<KPISectionType> createKPISection(KPISectionType value) {
        return new JAXBElement<KPISectionType>(_KPISection_QNAME, KPISectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeploymentSectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.telefonica.com/claudia/ovf", name = "DeploymentSection", substitutionHeadNamespace = "http://schemas.dmtf.org/ovf/envelope/1", substitutionHeadName = "Section")
    public JAXBElement<DeploymentSectionType> createDeploymentSection(DeploymentSectionType value) {
        return new JAXBElement<DeploymentSectionType>(_DeploymentSection_QNAME, DeploymentSectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoadBalancerSectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.telefonica.com/claudia/ovf", name = "LoadBalancerSection", substitutionHeadNamespace = "http://schemas.dmtf.org/ovf/envelope/1", substitutionHeadName = "Section")
    public JAXBElement<LoadBalancerSectionType> createLoadBalancerSection(LoadBalancerSectionType value) {
        return new JAXBElement<LoadBalancerSectionType>(_LoadBalancerSection_QNAME, LoadBalancerSectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AffinitySectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.telefonica.com/claudia/ovf", name = "AffinitySection", substitutionHeadNamespace = "http://schemas.dmtf.org/ovf/envelope/1", substitutionHeadName = "Section")
    public JAXBElement<AffinitySectionType> createAffinitySection(AffinitySectionType value) {
        return new JAXBElement<AffinitySectionType>(_AffinitySection_QNAME, AffinitySectionType.class, null, value);
    }
    
    /**
     * Create an instance of {@link PerformanceObjectiveSectionType }
     * 
     */
    public PerformanceObjectiveSectionType createPerformanceObjectiveSectionType() {
        return new PerformanceObjectiveSectionType();
    }

    /**
     * Create an instance of {@link AvailabilitySectionType }
     * 
     */
    public AvailabilitySectionType createAvailabilitySectionType() {
        return new AvailabilitySectionType();
    }
    
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AvailabilitySectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.telefonica.com/claudia/ovf", name = "AvailabilitySection", substitutionHeadNamespace = "http://schemas.dmtf.org/ovf/envelope/1", substitutionHeadName = "Section")
    public JAXBElement<AvailabilitySectionType> createAvailabilitySection(AvailabilitySectionType value) {
        return new JAXBElement<AvailabilitySectionType>(_AvailabilitySection_QNAME, AvailabilitySectionType.class, null, value);
    }


}
