#!/bin/bash

# Claudia Project
# http://claudia.morfeo-project.org
#
# (C) Copyright 2010 Telefonica Investigacion y Desarrollo
# S.A.Unipersonal (Telefonica I+D)
#
# See CREDITS file for info about members and contributors.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the Affero GNU General Public License (AGPL) as 
# published by the Free Software Foundation; either version 3 of the License, 
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the Affero GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#
# If you want to use this software an plan to distribute a
# proprietary application in any way, and you are not licensing and
# distributing your source code under AGPL, you probably need to
# purchase a commercial license of the product. Please contact
# claudia-support@lists.morfeo-project.org for more information.


# Claudia Service Manager Layer tester
#####################################################
ERROR_JAVA_NOT_FOUND=2

# Check that a Java Runtime Environment is in the PATH
WICH_RESULT=$(which java);
if [ $? == 1 ]; then
	
	echo -e "Java command not found. Check there is a Java Runtime Environment present, and the executable is in the PATH\n";

	exit $ERROR_JAVA_NOT_FOUND;
fi

cd "`dirname $0`";
cd ..; 

claudiaClib=$(ls lib/claudiaHelloWorld*.jar)
#echo $claudiaClib

#java -Djava.security.policy=conf/server.policy -jar lib/claudia-client-0.1.1.jar $1 $2;
java -Djava.security.policy=conf/server.policy -jar $claudiaClib $1 $2;
#java -Djava.security.policy=conf/server.policy -jar -Djava.util.logging.config.file=conf/log4j.properties $claudiaClib $1 $2;

