//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.12 at 03:51:35 PM CET 
//


package org.dmtf.schemas.wbem.wscim._1.cim_schema._2.cim_softwareelement;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.dmtf.schemas.wbem.wscim._1.common.CimDateTime;
import org.dmtf.schemas.wbem.wscim._1.common.CimString;


/**
 * <p>Java class for CIM_SoftwareElement_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CIM_SoftwareElement_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareElement}BuildNumber" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareElement}Caption" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareElement}CodeSet" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareElement}CommunicationStatus" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareElement}Description" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareElement}DetailedStatus" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareElement}ElementName" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareElement}HealthState" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareElement}IdentificationCode" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareElement}InstallDate" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareElement}InstanceID" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareElement}LanguageEdition" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareElement}Manufacturer" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareElement}Name"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareElement}OperatingStatus" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareElement}OperationalStatus" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareElement}OtherTargetOS" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareElement}PrimaryStatus" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareElement}SerialNumber" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareElement}SoftwareElementID"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareElement}SoftwareElementState"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareElement}Status" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareElement}StatusDescriptions" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareElement}TargetOperatingSystem"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareElement}Version"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CIM_SoftwareElement_Type", propOrder = {
    "buildNumber",
    "caption",
    "codeSet",
    "communicationStatus",
    "description",
    "detailedStatus",
    "elementName",
    "healthState",
    "identificationCode",
    "installDate",
    "instanceID",
    "languageEdition",
    "manufacturer",
    "name",
    "operatingStatus",
    "operationalStatus",
    "otherTargetOS",
    "primaryStatus",
    "serialNumber",
    "softwareElementID",
    "softwareElementState",
    "status",
    "statusDescriptions",
    "targetOperatingSystem",
    "version"
})
@XmlSeeAlso({
    com.telefonica.schemas.nuba_model.exp.CIMSoftwareElementType.class
})
public class CIMSoftwareElementType {

    @XmlElement(name = "BuildNumber", nillable = true)
    protected BuildNumber buildNumber;
    @XmlElement(name = "Caption", nillable = true)
    protected Caption caption;
    @XmlElement(name = "CodeSet", nillable = true)
    protected CodeSet codeSet;
    @XmlElement(name = "CommunicationStatus", nillable = true)
    protected CommunicationStatus communicationStatus;
    @XmlElement(name = "Description", nillable = true)
    protected CimString description;
    @XmlElement(name = "DetailedStatus", nillable = true)
    protected DetailedStatus detailedStatus;
    @XmlElement(name = "ElementName", nillable = true)
    protected CimString elementName;
    @XmlElement(name = "HealthState", nillable = true)
    protected HealthState healthState;
    @XmlElement(name = "IdentificationCode", nillable = true)
    protected IdentificationCode identificationCode;
    @XmlElement(name = "InstallDate", nillable = true)
    protected CimDateTime installDate;
    @XmlElement(name = "InstanceID", nillable = true)
    protected CimString instanceID;
    @XmlElement(name = "LanguageEdition", nillable = true)
    protected LanguageEdition languageEdition;
    @XmlElement(name = "Manufacturer", nillable = true)
    protected Manufacturer manufacturer;
    @XmlElement(name = "Name", required = true)
    protected Name name;
    @XmlElement(name = "OperatingStatus", nillable = true)
    protected OperatingStatus operatingStatus;
    @XmlElement(name = "OperationalStatus", nillable = true)
    protected List<OperationalStatus> operationalStatus;
    @XmlElement(name = "OtherTargetOS", nillable = true)
    protected OtherTargetOS otherTargetOS;
    @XmlElement(name = "PrimaryStatus", nillable = true)
    protected PrimaryStatus primaryStatus;
    @XmlElement(name = "SerialNumber", nillable = true)
    protected SerialNumber serialNumber;
    @XmlElement(name = "SoftwareElementID", required = true)
    protected SoftwareElementID softwareElementID;
    @XmlElement(name = "SoftwareElementState", required = true)
    protected SoftwareElementState softwareElementState;
    @XmlElement(name = "Status", nillable = true)
    protected Status status;
    @XmlElement(name = "StatusDescriptions", nillable = true)
    protected List<CimString> statusDescriptions;
    @XmlElement(name = "TargetOperatingSystem", required = true)
    protected TargetOperatingSystem targetOperatingSystem;
    @XmlElement(name = "Version", required = true)
    protected Version version;

    /**
     * Gets the value of the buildNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BuildNumber }
     *     
     */
    public BuildNumber getBuildNumber() {
        return buildNumber;
    }

    /**
     * Sets the value of the buildNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BuildNumber }
     *     
     */
    public void setBuildNumber(BuildNumber value) {
        this.buildNumber = value;
    }

    /**
     * Gets the value of the caption property.
     * 
     * @return
     *     possible object is
     *     {@link Caption }
     *     
     */
    public Caption getCaption() {
        return caption;
    }

    /**
     * Sets the value of the caption property.
     * 
     * @param value
     *     allowed object is
     *     {@link Caption }
     *     
     */
    public void setCaption(Caption value) {
        this.caption = value;
    }

    /**
     * Gets the value of the codeSet property.
     * 
     * @return
     *     possible object is
     *     {@link CodeSet }
     *     
     */
    public CodeSet getCodeSet() {
        return codeSet;
    }

    /**
     * Sets the value of the codeSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeSet }
     *     
     */
    public void setCodeSet(CodeSet value) {
        this.codeSet = value;
    }

    /**
     * Gets the value of the communicationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link CommunicationStatus }
     *     
     */
    public CommunicationStatus getCommunicationStatus() {
        return communicationStatus;
    }

    /**
     * Sets the value of the communicationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommunicationStatus }
     *     
     */
    public void setCommunicationStatus(CommunicationStatus value) {
        this.communicationStatus = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link CimString }
     *     
     */
    public CimString getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link CimString }
     *     
     */
    public void setDescription(CimString value) {
        this.description = value;
    }

    /**
     * Gets the value of the detailedStatus property.
     * 
     * @return
     *     possible object is
     *     {@link DetailedStatus }
     *     
     */
    public DetailedStatus getDetailedStatus() {
        return detailedStatus;
    }

    /**
     * Sets the value of the detailedStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link DetailedStatus }
     *     
     */
    public void setDetailedStatus(DetailedStatus value) {
        this.detailedStatus = value;
    }

    /**
     * Gets the value of the elementName property.
     * 
     * @return
     *     possible object is
     *     {@link CimString }
     *     
     */
    public CimString getElementName() {
        return elementName;
    }

    /**
     * Sets the value of the elementName property.
     * 
     * @param value
     *     allowed object is
     *     {@link CimString }
     *     
     */
    public void setElementName(CimString value) {
        this.elementName = value;
    }

    /**
     * Gets the value of the healthState property.
     * 
     * @return
     *     possible object is
     *     {@link HealthState }
     *     
     */
    public HealthState getHealthState() {
        return healthState;
    }

    /**
     * Sets the value of the healthState property.
     * 
     * @param value
     *     allowed object is
     *     {@link HealthState }
     *     
     */
    public void setHealthState(HealthState value) {
        this.healthState = value;
    }

    /**
     * Gets the value of the identificationCode property.
     * 
     * @return
     *     possible object is
     *     {@link IdentificationCode }
     *     
     */
    public IdentificationCode getIdentificationCode() {
        return identificationCode;
    }

    /**
     * Sets the value of the identificationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentificationCode }
     *     
     */
    public void setIdentificationCode(IdentificationCode value) {
        this.identificationCode = value;
    }

    /**
     * Gets the value of the installDate property.
     * 
     * @return
     *     possible object is
     *     {@link CimDateTime }
     *     
     */
    public CimDateTime getInstallDate() {
        return installDate;
    }

    /**
     * Sets the value of the installDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link CimDateTime }
     *     
     */
    public void setInstallDate(CimDateTime value) {
        this.installDate = value;
    }

    /**
     * Gets the value of the instanceID property.
     * 
     * @return
     *     possible object is
     *     {@link CimString }
     *     
     */
    public CimString getInstanceID() {
        return instanceID;
    }

    /**
     * Sets the value of the instanceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link CimString }
     *     
     */
    public void setInstanceID(CimString value) {
        this.instanceID = value;
    }

    /**
     * Gets the value of the languageEdition property.
     * 
     * @return
     *     possible object is
     *     {@link LanguageEdition }
     *     
     */
    public LanguageEdition getLanguageEdition() {
        return languageEdition;
    }

    /**
     * Sets the value of the languageEdition property.
     * 
     * @param value
     *     allowed object is
     *     {@link LanguageEdition }
     *     
     */
    public void setLanguageEdition(LanguageEdition value) {
        this.languageEdition = value;
    }

    /**
     * Gets the value of the manufacturer property.
     * 
     * @return
     *     possible object is
     *     {@link Manufacturer }
     *     
     */
    public Manufacturer getManufacturer() {
        return manufacturer;
    }

    /**
     * Sets the value of the manufacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Manufacturer }
     *     
     */
    public void setManufacturer(Manufacturer value) {
        this.manufacturer = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link Name }
     *     
     */
    public Name getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link Name }
     *     
     */
    public void setName(Name value) {
        this.name = value;
    }

    /**
     * Gets the value of the operatingStatus property.
     * 
     * @return
     *     possible object is
     *     {@link OperatingStatus }
     *     
     */
    public OperatingStatus getOperatingStatus() {
        return operatingStatus;
    }

    /**
     * Sets the value of the operatingStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperatingStatus }
     *     
     */
    public void setOperatingStatus(OperatingStatus value) {
        this.operatingStatus = value;
    }

    /**
     * Gets the value of the operationalStatus property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the operationalStatus property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOperationalStatus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OperationalStatus }
     * 
     * 
     */
    public List<OperationalStatus> getOperationalStatus() {
        if (operationalStatus == null) {
            operationalStatus = new ArrayList<OperationalStatus>();
        }
        return this.operationalStatus;
    }

    /**
     * Gets the value of the otherTargetOS property.
     * 
     * @return
     *     possible object is
     *     {@link OtherTargetOS }
     *     
     */
    public OtherTargetOS getOtherTargetOS() {
        return otherTargetOS;
    }

    /**
     * Sets the value of the otherTargetOS property.
     * 
     * @param value
     *     allowed object is
     *     {@link OtherTargetOS }
     *     
     */
    public void setOtherTargetOS(OtherTargetOS value) {
        this.otherTargetOS = value;
    }

    /**
     * Gets the value of the primaryStatus property.
     * 
     * @return
     *     possible object is
     *     {@link PrimaryStatus }
     *     
     */
    public PrimaryStatus getPrimaryStatus() {
        return primaryStatus;
    }

    /**
     * Sets the value of the primaryStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrimaryStatus }
     *     
     */
    public void setPrimaryStatus(PrimaryStatus value) {
        this.primaryStatus = value;
    }

    /**
     * Gets the value of the serialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link SerialNumber }
     *     
     */
    public SerialNumber getSerialNumber() {
        return serialNumber;
    }

    /**
     * Sets the value of the serialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link SerialNumber }
     *     
     */
    public void setSerialNumber(SerialNumber value) {
        this.serialNumber = value;
    }

    /**
     * Gets the value of the softwareElementID property.
     * 
     * @return
     *     possible object is
     *     {@link SoftwareElementID }
     *     
     */
    public SoftwareElementID getSoftwareElementID() {
        return softwareElementID;
    }

    /**
     * Sets the value of the softwareElementID property.
     * 
     * @param value
     *     allowed object is
     *     {@link SoftwareElementID }
     *     
     */
    public void setSoftwareElementID(SoftwareElementID value) {
        this.softwareElementID = value;
    }

    /**
     * Gets the value of the softwareElementState property.
     * 
     * @return
     *     possible object is
     *     {@link SoftwareElementState }
     *     
     */
    public SoftwareElementState getSoftwareElementState() {
        return softwareElementState;
    }

    /**
     * Sets the value of the softwareElementState property.
     * 
     * @param value
     *     allowed object is
     *     {@link SoftwareElementState }
     *     
     */
    public void setSoftwareElementState(SoftwareElementState value) {
        this.softwareElementState = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link Status }
     *     
     */
    public Status getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link Status }
     *     
     */
    public void setStatus(Status value) {
        this.status = value;
    }

    /**
     * Gets the value of the statusDescriptions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the statusDescriptions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStatusDescriptions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CimString }
     * 
     * 
     */
    public List<CimString> getStatusDescriptions() {
        if (statusDescriptions == null) {
            statusDescriptions = new ArrayList<CimString>();
        }
        return this.statusDescriptions;
    }

    /**
     * Gets the value of the targetOperatingSystem property.
     * 
     * @return
     *     possible object is
     *     {@link TargetOperatingSystem }
     *     
     */
    public TargetOperatingSystem getTargetOperatingSystem() {
        return targetOperatingSystem;
    }

    /**
     * Sets the value of the targetOperatingSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link TargetOperatingSystem }
     *     
     */
    public void setTargetOperatingSystem(TargetOperatingSystem value) {
        this.targetOperatingSystem = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link Version }
     *     
     */
    public Version getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link Version }
     *     
     */
    public void setVersion(Version value) {
        this.version = value;
    }

}
