//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.12 at 03:51:35 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_SoftwareElement", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.dmtf.schemas.wbem.wscim._1.cim_schema._2.cim_softwareelement;
