#!/bin/bash

# Claudia Project
# http://claudia.morfeo-project.org
#
# (C) Copyright 2010 Telefonica Investigacion y Desarrollo
# S.A.Unipersonal (Telefonica I+D)
#
# See CREDITS file for info about members and contributors.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the Affero GNU General Public License (AGPL) as 
# published by the Free Software Foundation; either version 3 of the License, 
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the Affero GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#
# If you want to use this software an plan to distribute a
# proprietary application in any way, and you are not licensing and
# distributing your source code under AGPL, you probably need to
# purchase a commercial license of the product. Please contact
# claudia-support@lists.morfeo-project.org for more information.


function setProp {
        echo -e "\t- Setting $1 = $2 into $3";
        sed s/"$1".*=.*$/"$1"="$2"/ $3 > $3.b1;
        mv $3.b1 $3;
}

cd "`dirname $0`";
cd ..;

echo -e "* Creating directories\n";
CLAUDIA_CONF_FILE=conf/claudiaClient.properties

ENVIRONMENT_DISK=$(cat $CLAUDIA_CONF_FILE|grep claudia.environment.disk | awk -F = '{print $2}');
ENVIRONMENT_FOLDER=$(cat $CLAUDIA_CONF_FILE|grep claudia.environment.folder| awk -F = '{print $2}');

mkdir $ENVIRONMENT_FOLDER
mount $ENVIRONMENT_DISK $ENVIRONMENT_FOLDER

function getValue {
        echo "Getting value: $1";
	AWK_PROGRAM=$(cat bin/awkProg |sed "s/@KPICHANNELNAME/$1/")
	GLOBAL_RESULT=$(xmllint -format $ENVIRONMENT_FOLDER/ovf-env.xml | awk "$AWK_PROGRAM")
}

# Check out the environment properties and set up environment
echo -e "* Setting up environment\n";
getValue "ExternalIP"
PUBLIC_IP=$GLOBAL_RESULT

getValue "InternalIP"
INTERNAL_IP=$GLOBAL_RESULT

getValue "ExternalMask"
PUBLIC_MASK=$GLOBAL_RESULT

getValue "InternalMask"
INTERNAL_MASK=$GLOBAL_RESULT

echo -e "* Configuring interfaces\n";
cp conf/templateInterfaces tmpInterfaces
sed s/@DEV/"eth1"/ tmpInterfaces > tmpInterfaces.tmp
mv tmpInterfaces.tmp tmpInterfaces
sed s/@NETWORK/"10.95.240.4"/ tmpInterfaces > tmpInterfaces.tmp
mv tmpInterfaces.tmp tmpInterfaces
sed s/@IP/"$PUBLIC_IP"/ tmpInterfaces > tmpInterfaces.tmp
mv tmpInterfaces.tmp tmpInterfaces
sed s/@NETMASK/"$PUBLIC_MASK"/ tmpInterfaces > tmpInterfaces.tmp
mv tmpInterfaces.tmp tmpInterfaces
cat tmpInterfaces >> /etc/network/interfaces
rm tmpInterfaces

cp conf/templateInterfaces tmpInterfaces
sed s/@DEV/"eth1:1"/ tmpInterfaces > tmpInterfaces.tmp
mv tmpInterfaces.tmp tmpInterfaces
sed s/@NETWORK/"192.168.0.16"/ tmpInterfaces > tmpInterfaces.tmp
mv tmpInterfaces.tmp tmpInterfaces
sed s/@IP/"$INTERNAL_IP"/ tmpInterfaces > tmpInterfaces.tmp
mv tmpInterfaces.tmp tmpInterfaces
sed s/@NETMASK/"$INTERNAL_MASK"/ tmpInterfaces > tmpInterfaces.tmp
mv tmpInterfaces.tmp tmpInterfaces
cat tmpInterfaces >> /etc/network/interfaces
rm tmpInterfaces

ifup eth1

echo -e "* Creating actions program\n";
AWK_PROGRAM=$(cat bin/awkProg |sed "s/@KPICHANNELNAME/KPIChannel/")
KPI_CHANNEL=$(xmllint -format $ENVIRONMENT_FOLDER/ovf-env.xml | awk "$AWK_PROGRAM")

setProp rest.host $KPI_CHANNEL $CLAUDIA_CONF_FILE 

getValue "KPITimesUrl"
KPI_URL=$GLOBAL_RESULT

getValue "KPIName"
KPI_NAME=$GLOBAL_RESULT

wget $KPI_URL;
cat times |awk '{print $1":"$2":"$3":event(agent, @KPINAME, "$4")"}' | sed s/@KPINAME/$KPI_NAME/ > actions

