#!/bin/bash
#
# tcloudd - tcloud  Daemon
#
# chkconfig: - 85 15
# description: Tcloud component of claudia 
# processname: tcloud 
# config: /etc/claudia/conf/tcloud.properties
#

case "$1" in
  start)
        echo "Starting tcloud daemon"

        nohup /opt/claudia/bin/tcloud $1 >& /var/log/tcloud.log  &
;;
  stop)
        echo "Stopping tcloud daemon"
        nohup /opt/claudia/bin/tcloud $1  >& /var/log/tcloud.log  & 
        ;;
restart)
        echo "Stopping tcloud daemon"
        nohup /opt/claudia/bin/tcloud stop >& /var/log/tcloud.log  &
        sleep 5
        echo "Starting tcloud daemon"
        nohup /opt/claudia/bin/tcloud start >& /var/log/tcloud.log  &
        sleep 5

;;
esac
exit 0
