#!/bin/bash

###################################################################
## TCloud Server Daemon
###################################################################

# Constant declarations
ERROR_USAGE=1
ERROR_JAVA_NOT_FOUND=2

# Depending on the arguments start, or stop the server
if [ $# -ne 1 ]; then

    echo -e "Starts or stop the TCloud Server daemon: \n";
    echo -e "\t\t$0 {start|stop}\n";

    exit $ERROR_USAGE;
fi

cd "`dirname $0`";
cd "../lib";
tcloudlib=$(ls tcloud-server-*.jar);
cd ..; 

if [ $1 == "start" ]; then

    # Check that a Java Runtime Environment is in the PATH
    WICH_RESULT=$(which java);
    if [ $? == 1 ]; then
    
        echo -e "Java command not found. Check there is a Java Runtime Environment present, and the executable is in the PATH\n";

        exit $ERROR_JAVA_NOT_FOUND;
    fi  

    # Run the Server class
    echo "Initiating TCloud Server";
    #java -jar lib/tcloud-server-0.1.1.jar;
    java -jar "lib/"$tcloudlib;
    
    echo "Shutting down TCloud Server";

elif [ $1 == "stop" ]; then 

    # TODO: too hard way to kill a server. Pending solution.
    #ps -ef |grep tcloud-server-0.1.1.jar | grep -v grep |awk '{print $2}'|xargs -I '{}' kill -9 '{}'
    ps -ef |grep $tcloudlib | grep -v grep |awk '{print $2}'|xargs -I '{}' kill -9 '{}'
    echo "Stopping TCloud Server, please, wait";
fi
