#!/bin/sh

export HOSTNAME=`hostname` 
sed -i  "s/localhost/$HOSTNAME/g" /opt/claudia/conf/sm.properties


    echo "Please, enter the virtual data network config:";
    echo " Public network: e.g.: 212.189.207.208";
    read -e RESERVOIR_NETWORK
    echo "Public network netmask: e.g.: 255.255.255.240";
    read -e RESERVOIR_NETMASK
    echo "Public network gateway: e.g.: 212.189.207.193";
    read -e RESERVOIR_GATEWAY
    echo "Public network dns: e.g.: 212.189.207.217";
    read -e RESERVOIR_DNS

    echo "Public ip list: e.g.: 212.189.207.216/212.189.207.217/212.189.207.218/212.189.207.219/212.189.207.220/212.189.207.221/212.189.207.222/";
    read -e IP_LIST;


    echo "Please, enter the virtual data network config:";
    echo "Private network: e.g.: 192.168.0.0";
    read -e RESERVOIR_PRIVATE_NETWORK
    echo "Private network netmask: e.g.: 255.255.240.0";
    read -e RESERVOIR_PRIVATE_NETMASK
    echo "Private network gateway: e.g.: 192.168.1.1";
    read -e RESERVOIR_PRIVATE_GATEWAY
    echo "Private network dns: e.g.: 192.168.1.1";
    read -e RESERVOIR_PRIVATE_DNS

sed -i  "s/RESERVOIR_NETWORK/$RESERVOIR_NETWORK/g" /opt/claudia/conf/sm.properties
sed -i  "s/RESERVOIR_NETMASK/$RESERVOIR_NETMASK/g" /opt/claudia/conf/sm.properties
sed -i  "s/RESERVOIR_GATEWAY/$RESERVOIR_GATEWAY/g" /opt/claudia/conf/sm.properties
sed -i  "s/RESERVOIR_DNS/$RESERVOIR_DNS/g" /opt/claudia/conf/sm.properties
sed -i  "s,IP_LIST,$IP_LIST,g" /opt/claudia/conf/sm.properties

sed -i  "s/RESERVOIR_PRIVATE_NETWORK/$RESERVOIR_PRIVATE_NETWORK/g" /opt/claudia/conf/sm.properties
sed -i  "s/RESERVOIR_PRIVATE_NETMASK/$RESERVOIR_PRIVATE_NETMASK/g" /opt/claudia/conf/sm.properties
sed -i  "s/RESERVOIR_PRIVATE_GATEWAY/$RESERVOIR_PRIVATE_GATEWAY/g" /opt/claudia/conf/sm.properties
sed -i  "s/RESERVOIR_PRIVATE_DNS/$RESERVOIR_PRIVATE_DNS/g" /opt/claudia/conf/sm.properties

echo -ne "\nPlease enter the new SiteRoot that will be used to prefix the servirce id in the Service Manager, e.g. ThereSIS.thales, it.Unime, se.Umea: "
 read siteroot

sed -i "s;SiteRoot.*;SiteRoot $siteroot;" /opt/claudia/conf/sm.properties

